In [9]:
import pandas as pd

In [10]:
df = pd.read_excel("../Archived/RSA.xlsx")

In [11]:
df

,Galaxy,RA,Dec,Type,BT,Ai,v,ɛ,classes
0,-1.0,-3.0,-4.0,-9.0,-12.00,-14.00,-17.0,-18.0,NaN
1,F703,15 11 00,-15 16.7,S S5 2.2,-12.41,0.34,2270.0,15.0,Sx
2,HA72,13 57 39,-45 10.6,S S5 2.5,-12.83,0.38,1456.0,50.0,Sx
3,HA85-1,05 09 25,-14 51.0,S S5 2.0,-12.69,0.35,2140.0,165.0,Sx
4,HA85-2,18 52 53,-54 36.9,E 3,12.65,0.00,2761.0,113.0,E3
...,...,...,...,...,...,...,...,...,...
1243,NGC986,02 31 34,-39 15.9,SB T3 1.5,11.80,0.59,2073.0,200.0,SBx
1244,NGC991,02 33 03,-07 22.0,S T5 2.0,-12.42,0.30,1530.0,15.0,Sx
1245,NGC4517A,12 29 55,00 39.9,S 7 4.0,12.65,0.40,1521.0,28.0,Sx
1246,SMC,00 51 00,-73 06.,I 9 4.5,2.79,0.25,163.0,5.0,I
1247,NaN,-1950.0,-1950.0,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
print(df)

        Galaxy        RA       Dec       Type     BT     Ai       v      ɛ  \
0         -1.0      -3.0      -4.0       -9.0 -12.00 -14.00   -17.0  -18.0
1         F703  15 11 00  -15 16.7   S S5 2.2 -12.41   0.34  2270.0   15.0
2         HA72  13 57 39  -45 10.6   S S5 2.5 -12.83   0.38  1456.0   50.0
3       HA85-1  05 09 25  -14 51.0   S S5 2.0 -12.69   0.35  2140.0  165.0
4       HA85-2  18 52 53  -54 36.9        E 3  12.65   0.00  2761.0  113.0
...        ...       ...       ...        ...    ...    ...     ...    ...
1243    NGC986  02 31 34  -39 15.9  SB T3 1.5  11.80   0.59  2073.0  200.0
1244    NGC991  02 33 03  -07 22.0   S T5 2.0 -12.42   0.30  1530.0   15.0
1245  NGC4517A  12 29 55   00 39.9    S 7 4.0  12.65   0.40  1521.0   28.0
1246       SMC  00 51 00   -73 06.    I 9 4.5   2.79   0.25   163.0    5.0
1247       NaN   -1950.0   -1950.0        NaN    NaN    NaN     NaN    NaN

     classes
0        NaN
1         Sx
2         Sx
3         Sx
4         E3
...      ...
1243     SBx
1244      Sx
1245      Sx
1246       I
1247     NaN

[1248 rows x 9 columns]

In [13]:
df["Type"]

0            -9.0
1        S S5 2.2
2        S S5 2.5
3        S S5 2.0
4             E 3
          ...
1243    SB T3 1.5
1244     S T5 2.0
1245      S 7 4.0
1246      I 9 4.5
1247          NaN
Name: Type, Length: 1248, dtype: object

In [14]:
mainclass = []
subclass = []
for i in df["Type"]:
    pars = str(i)
    parslist = pars.split(sep=" ")
    if len(parslist)>1:
        mainclass.append(parslist[0])
        subclass.append(parslist[1])
    else:
        mainclass.append(parslist[0])
        subclass.append("irrelevant")
df['MainClass'] = mainclass
df['SubClass'] = subclass
df

,Galaxy,RA,Dec,Type,BT,Ai,v,ɛ,classes,MainClass,SubClass
0,-1.0,-3.0,-4.0,-9.0,-12.00,-14.00,-17.0,-18.0,NaN,-9.0,irrelevant
1,F703,15 11 00,-15 16.7,S S5 2.2,-12.41,0.34,2270.0,15.0,Sx,S,S5
2,HA72,13 57 39,-45 10.6,S S5 2.5,-12.83,0.38,1456.0,50.0,Sx,S,S5
3,HA85-1,05 09 25,-14 51.0,S S5 2.0,-12.69,0.35,2140.0,165.0,Sx,S,S5
4,HA85-2,18 52 53,-54 36.9,E 3,12.65,0.00,2761.0,113.0,E3,E,3
...,...,...,...,...,...,...,...,...,...,...,...
1243,NGC986,02 31 34,-39 15.9,SB T3 1.5,11.80,0.59,2073.0,200.0,SBx,SB,T3
1244,NGC991,02 33 03,-07 22.0,S T5 2.0,-12.42,0.30,1530.0,15.0,Sx,S,T5
1245,NGC4517A,12 29 55,00 39.9,S 7 4.0,12.65,0.40,1521.0,28.0,Sx,S,7
1246,SMC,00 51 00,-73 06.,I 9 4.5,2.79,0.25,163.0,5.0,I,I,9
1247,NaN,-1950.0,-1950.0,NaN,NaN,NaN,NaN,NaN,NaN,nan,irrelevant

In [16]:
df.to_csv("../ProcessedRSA.csv")
df.to_excel("../ProcessedRSA.xlsx")

In [17]:
Class = []
ClassInt = []
for i in df["MainClass"]:
    pars = str(i)
    if(pars[0].upper() in ['-','1','2','3','4','5','6','7','8','9']):
        Class.append("Irrelevant")
        ClassInt.append(-1)
    elif(pars[0].upper()=="S"):
        Class.append("Spiral")
        ClassInt.append(0)
    elif(pars[0].upper()=="E"):
        Class.append("Elliptical")
        ClassInt.append(1)
    elif("B" in pars):
        Class.append("Spiral")
        ClassInt.append(0)
    else:
        Class.append("Irregular")
        ClassInt.append(2)
Class
ClassInt

[-1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 2,
 0,
 0,
 2,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 1,
 2,
 1,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 1,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 1,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 2,
 1,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 2,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 1,
 2,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 1,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 2,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 0,
 2,
 0,
 2,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 2,
 0,
 2,
 0,
 2,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 2,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 0,
 1,
 2,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 1,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 2,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 1,
 0,
 2,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 0,
 0,
 1,
 1,
 2,
 0,
 2,
 0,
 2,
 2,
 0,
 2,
 0,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 1,
 2,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 0,
 1,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 2,
 0,
 2,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 2,
 0,
 1,
 0,
 2,
 1,
 1,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 ...]

In [ ]:
df['Class'] = Class

In [ ]:
df["ClassInt"] = ClassInt

In [ ]:
df.to_csv("../ProcessedSimplifiedRSA.csv")
df.to_excel("../ProcessedSimplifiedRSA.xlsx")